### ISSUE TITLE
Can't import iriweb module

### ISSUE THREAD

**Issue by ljlamarche** [rilma/pyIRI2016#23]
When running `example01.py`, I get the following error:
```
Traceback (most recent call last):
  File "/Users/e30737/Desktop/Software/pyIRI2016/examples/example01.py", line 15, in <module>
    main1()
  File "/Users/e30737/Desktop/Software/pyIRI2016/examples/example01.py", line 10, in main1
    IRIData, IRIDATAAdd = Obj.IRI()
  File "/Users/e30737/Desktop/Software/pyIRI2016/pyiri2016/__init__.py", line 81, in IRI
    hh, mm, ss = TimeUtilities().ToHMS(hrlt)
NameError: name 'TimeUtilities' is not defined
```
TimeUtilities is installed, but it is not being imported due to this try-except statement in `__init__.py` which fails to import iriwebg.

```
try:
    from .iriweb import iriwebg
    from timeutil import TimeUtilities
except ModuleNotFoundError:
    pass    # TODO
```
When the exception is printed, it produces `No module named 'pyiri2016.iriweb'`, which I think suggests that the iriweb extension is not being built correctly when pyiri2016 is installed.

**Comment by Zlydzen** [comment]
the same problem!

**Comment by w2naf** [comment]
@rilma Same problem here! Has there been any progress on this?

**Comment by Adim-a11y** [comment]
NameError: name 'iriwebg' is not defined
